export type {
  AppSettings as WorkspaceSettings,
  BootstrapSnapshot,
  GridDefinition,
  LayoutPreset,
  NewTabRequest,
  PaneLifecycleEvent,
  PaneProfile,
  PaneRuntimeStatus,
  PaneSnapshot,
  PtyOutputEvent,
  PtyResizeRequest,
  TabSnapshot,
  ThemeMode,
  UpdatePaneCwdRequest,
  UpdatePaneProfileRequest,
  WorkspaceChangedEvent,
  WorkspaceSnapshot,
} from "@/lib/tauri-bindings";
