
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppSettings() : Promise<Result<AppSettings, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppSettings(settings: AppSettings) : Promise<Result<AppSettings, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bootstrapWorkspace() : Promise<Result<BootstrapSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTab(request: NewTabRequest) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_tab", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTab(tabId: string) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_tab", { tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveTab(tabId: string) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_tab", { tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusPane(tabId: string, paneId: string) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_pane", { tabId, paneId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartPane(paneId: string) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_pane", { paneId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePaneProfile(request: UpdatePaneProfileRequest) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_pane_profile", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePaneCwd(request: UpdatePaneCwdRequest) : Promise<Result<WorkspaceSnapshot, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_pane_cwd", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writePty(paneId: string, data: string) : Promise<Result<null, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_pty", { paneId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizePty(request: PtyResizeRequest) : Promise<Result<null, TabbyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_pty", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { defaultLayout: LayoutPreset; defaultProfileId: string; defaultWorkingDirectory: string; defaultCustomCommand: string; fontSize: number; theme: ThemeMode; launchFullscreen: boolean; hasCompletedOnboarding?: boolean }
export type BootstrapSnapshot = { workspace: WorkspaceSnapshot; settings: AppSettings; profiles: PaneProfile[] }
export type GridDefinition = { preset: LayoutPreset; rows: number; columns: number; paneCount: number }
export type LayoutPreset = "1x1" | "1x2" | "2x2" | "2x3" | "3x3"
export type NewTabRequest = { preset: LayoutPreset; cwd: string | null; profileId: string | null; startupCommand: string | null }
export type PaneLifecycleEvent = { paneId: string; sessionId: string | null; status: PaneRuntimeStatus; errorMessage: string | null }
export type PaneProfile = { id: string; label: string; description: string; startupCommand: string | null }
export type PaneRuntimeStatus = "starting" | "running" | "restarting" | "exited" | "failed"
export type PaneSnapshot = { id: string; sessionId: string; title: string; cwd: string; profileId: string; profileLabel: string; startupCommand: string | null; status: PaneRuntimeStatus }
export type PtyOutputEvent = { paneId: string; sessionId: string; chunk: string }
export type PtyResizeRequest = { paneId: string; cols: number; rows: number }
export type TabSnapshot = { id: string; title: string; preset: LayoutPreset; panes: PaneSnapshot[]; activePaneId: string }
export type TabbyError = { Validation: string } | { State: string } | { NotFound: string } | { Pty: string } | { Io: string } | { Store: string } | { Serialization: string }
export type ThemeMode = "system" | "dawn" | "midnight"
export type UpdatePaneCwdRequest = { paneId: string; cwd: string }
export type UpdatePaneProfileRequest = { paneId: string; profileId: string; startupCommand: string | null }
export type WorkspaceChangedEvent = { workspace: WorkspaceSnapshot }
export type WorkspaceSnapshot = { activeTabId: string; tabs: TabSnapshot[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
