
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async bootstrapShell() : Promise<Result<WorkspaceBootstrapView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_shell") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchWorkspaceCommand(command: WorkspaceCommandDto) : Promise<Result<WorkspaceView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_workspace_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchSettingsCommand(command: SettingsCommandDto) : Promise<Result<SettingsView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_settings_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchRuntimeCommand(command: RuntimeCommandDto) : Promise<Result<null, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_runtime_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchBrowserSurfaceCommand(command: BrowserSurfaceCommandDto) : Promise<Result<null, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_browser_surface_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BrowserLocationObservedEvent = { paneId: string; url: string }
export type BrowserSurfaceBoundsDto = { x: number; y: number; width: number; height: number }
export type BrowserSurfaceCommandDto = { kind: "ensure"; pane_id: string; url: string; bounds: BrowserSurfaceBoundsDto } | { kind: "setBounds"; pane_id: string; bounds: BrowserSurfaceBoundsDto } | { kind: "setVisible"; pane_id: string; visible: boolean } | { kind: "close"; pane_id: string }
export type LayoutPresetDto = "1x1" | "1x2" | "2x2" | "2x3" | "3x3"
export type PaneRuntimeView = { paneId: string; runtimeSessionId: string | null; kind: RuntimeKindDto; status: RuntimeStatusDto; lastError: string | null; browserLocation: string | null }
export type PaneSpecDto = { kind: "terminal"; launch_profile_id: string; working_directory: string; command_override: string | null } | { kind: "browser"; initial_url: string }
export type PaneView = { paneId: string; title: string; spec: PaneSpecDto }
export type ProfileCatalogView = { terminalProfiles: ProfileView[] }
export type ProfileView = { id: string; label: string; description: string; startupCommandTemplate: string | null }
export type RuntimeCommandDto = { kind: "writeTerminalInput"; pane_id: string; input: string } | { kind: "resizeTerminal"; pane_id: string; cols: number; rows: number } | { kind: "navigateBrowser"; pane_id: string; url: string } | { kind: "observeTerminalCwd"; pane_id: string; working_directory: string } | { kind: "observeBrowserLocation"; pane_id: string; url: string }
export type RuntimeKindDto = "terminal" | "browser"
export type RuntimeStatusChangedEvent = { runtime: PaneRuntimeView }
export type RuntimeStatusDto = "starting" | "running" | "exited" | "failed"
export type SettingsCommandDto = { kind: "update"; settings: SettingsView } | { kind: "reset" }
export type SettingsProjectionUpdatedEvent = { settings: SettingsView; profileCatalog: ProfileCatalogView }
export type SettingsView = { defaultLayout: LayoutPresetDto; defaultTerminalProfileId: string; defaultWorkingDirectory: string; defaultCustomCommand: string; fontSize: number; theme: ThemeModeDto; launchFullscreen: boolean; hasCompletedOnboarding: boolean; lastWorkingDirectory: string | null }
export type ShellError = { Validation: string } | { State: string } | { NotFound: string } | { Pty: string } | { Io: string } | { Store: string } | { Serialization: string }
export type SplitDirectionDto = "horizontal" | "vertical"
export type SplitNodeDto = { type: "pane"; paneId: string } | { type: "split"; direction: SplitDirectionDto; ratio: number; first: SplitNodeDto; second: SplitNodeDto }
export type TabView = { tabId: string; title: string; layout: SplitNodeDto; panes: PaneView[]; activePaneId: string }
export type TerminalOutputEvent = { paneId: string; runtimeSessionId: string; chunk: string }
export type ThemeModeDto = "system" | "dawn" | "midnight"
export type WorkspaceBootstrapView = { workspace: WorkspaceView; settings: SettingsView; profileCatalog: ProfileCatalogView; runtimeProjections: PaneRuntimeView[] }
export type WorkspaceCommandDto = { kind: "openTab"; layout: LayoutPresetDto | null; auto_layout: boolean; pane_specs: PaneSpecDto[] } | { kind: "closeTab"; tab_id: string } | { kind: "setActiveTab"; tab_id: string } | { kind: "focusPane"; tab_id: string; pane_id: string } | { kind: "splitPane"; pane_id: string; direction: SplitDirectionDto; pane_spec: PaneSpecDto } | { kind: "closePane"; pane_id: string } | { kind: "swapPaneSlots"; pane_id_a: string; pane_id_b: string } | { kind: "replacePaneSpec"; pane_id: string; pane_spec: PaneSpecDto } | { kind: "restartPaneRuntime"; pane_id: string }
export type WorkspaceProjectionUpdatedEvent = { workspace: WorkspaceView }
export type WorkspaceView = { activeTabId: string; tabs: TabView[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
