
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async bootstrapShell() : Promise<Result<WorkspaceBootstrapView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_shell") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchWorkspaceCommand(command: WorkspaceCommandDto) : Promise<Result<WorkspaceView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_workspace_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchSettingsCommand(command: SettingsCommandDto) : Promise<Result<SettingsView, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_settings_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchRuntimeCommand(command: RuntimeCommandDto) : Promise<Result<null, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_runtime_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchBrowserSurfaceCommand(command: BrowserSurfaceCommandDto) : Promise<Result<null, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_browser_surface_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dispatchGitCommand(command: GitCommandDto) : Promise<Result<GitResultDto, ShellError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_git_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BlameEntryDto = { hash: string; author: string; date: string; lineStart: number; lineCount: number; content: string }
export type BranchInfoDto = { name: string; isCurrent: boolean; upstream: string | null; ahead: number; behind: number }
export type BrowserSurfaceBoundsDto = { x: number; y: number; width: number; height: number }
export type BrowserSurfaceCommandDto = { kind: "ensure"; pane_id: string; url: string; bounds: BrowserSurfaceBoundsDto } | { kind: "setBounds"; pane_id: string; bounds: BrowserSurfaceBoundsDto } | { kind: "setVisible"; pane_id: string; visible: boolean } | { kind: "close"; pane_id: string }
export type CommitInfoDto = { hash: string; shortHash: string; authorName: string; authorEmail: string; date: string; message: string; parentHashes: string[] }
export type DiffContentDto = { filePath: string; oldPath: string | null; hunks: DiffHunkDto[]; isBinary: boolean; fileModeChange: string | null }
export type DiffHunkDto = { oldStart: number; oldCount: number; newStart: number; newCount: number; header: string; lines: DiffLineDto[] }
export type DiffLineDto = { kind: DiffLineKindDto; oldLineNo: number | null; newLineNo: number | null; content: string }
export type DiffLineKindDto = "context" | "addition" | "deletion" | "hunkHeader"
export type FileStatusDto = { path: string; oldPath: string | null; indexStatus: FileStatusKindDto; worktreeStatus: FileStatusKindDto }
export type FileStatusKindDto = "modified" | "added" | "deleted" | "renamed" | "copied" | "untracked" | "ignored" | "conflicted"
export type GitCommandDto = { kind: "status"; pane_id: string } | { kind: "diff"; pane_id: string; path: string | null; staged: boolean } | { kind: "stage"; pane_id: string; paths: string[] } | { kind: "unstage"; pane_id: string; paths: string[] } | { kind: "stageLines"; pane_id: string; path: string; line_ranges: string[] } | { kind: "commit"; pane_id: string; message: string; amend: boolean } | { kind: "push"; pane_id: string; remote: string | null; branch: string | null } | { kind: "pull"; pane_id: string; remote: string | null; branch: string | null } | { kind: "fetch"; pane_id: string; remote: string | null } | { kind: "branches"; pane_id: string } | { kind: "checkoutBranch"; pane_id: string; name: string } | { kind: "createBranch"; pane_id: string; name: string; start_point: string | null } | { kind: "deleteBranch"; pane_id: string; name: string; force: boolean } | { kind: "mergeBranch"; pane_id: string; name: string } | { kind: "log"; pane_id: string; max_count: number | null; skip: number | null; path: string | null } | { kind: "showCommit"; pane_id: string; hash: string } | { kind: "blame"; pane_id: string; path: string } | { kind: "stashPush"; pane_id: string; message: string | null } | { kind: "stashPop"; pane_id: string; index: number | null } | { kind: "stashList"; pane_id: string } | { kind: "stashDrop"; pane_id: string; index: number } | { kind: "discardChanges"; pane_id: string; paths: string[] } | { kind: "repoState"; pane_id: string }
export type GitRepoStateDto = { repoPath: string; headBranch: string | null; isDetached: boolean; statusClean: boolean }
export type GitResultDto = { kind: "status"; files: FileStatusDto[] } | { kind: "diff"; diffs: DiffContentDto[] } | { kind: "stage" } | { kind: "unstage" } | { kind: "stageLines" } | { kind: "commit"; hash: string } | { kind: "push" } | { kind: "pull" } | { kind: "fetch" } | { kind: "branches"; branches: BranchInfoDto[] } | { kind: "checkoutBranch" } | { kind: "createBranch" } | { kind: "deleteBranch" } | { kind: "mergeBranch"; message: string } | { kind: "log"; commits: CommitInfoDto[] } | { kind: "showCommit"; diffs: DiffContentDto[] } | { kind: "blame"; entries: BlameEntryDto[] } | { kind: "stashPush" } | { kind: "stashPop" } | { kind: "stashList"; entries: StashEntryDto[] } | { kind: "stashDrop" } | { kind: "discardChanges" } | { kind: "repoState"; state: GitRepoStateDto }
export type LayoutPresetDto = "1x1" | "1x2" | "2x2" | "2x3" | "3x3"
export type PaneRuntimeView = { paneId: string; runtimeSessionId: string | null; kind: RuntimeKindDto; status: RuntimeStatusDto; lastError: string | null; browserLocation: string | null; terminalCwd: string | null; gitRepoPath: string | null }
export type PaneSpecDto = { kind: "terminal"; launch_profile_id: string; working_directory: string; command_override: string | null } | { kind: "browser"; initial_url: string } | { kind: "git"; working_directory: string }
export type PaneView = { paneId: string; title: string; spec: PaneSpecDto }
export type ProfileCatalogView = { terminalProfiles: ProfileView[] }
export type ProfileView = { id: string; label: string; description: string; startupCommandTemplate: string | null }
export type RuntimeCommandDto = { kind: "writeTerminalInput"; pane_id: string; input: string } | { kind: "resizeTerminal"; pane_id: string; cols: number; rows: number } | { kind: "navigateBrowser"; pane_id: string; url: string } | { kind: "observeTerminalCwd"; pane_id: string; working_directory: string } | { kind: "observeBrowserLocation"; pane_id: string; url: string }
export type RuntimeKindDto = "terminal" | "browser" | "git"
export type RuntimeStatusChangedEvent = { runtime: PaneRuntimeView }
export type RuntimeStatusDto = "starting" | "running" | "exited" | "failed"
export type SettingsCommandDto = { kind: "update"; settings: SettingsView } | { kind: "reset" }
export type SettingsProjectionUpdatedEvent = { settings: SettingsView; profileCatalog: ProfileCatalogView }
export type SettingsView = { defaultLayout: LayoutPresetDto; defaultTerminalProfileId: string; defaultWorkingDirectory: string; defaultCustomCommand: string; fontSize: number; theme: ThemeModeDto; launchFullscreen: boolean; hasCompletedOnboarding: boolean; lastWorkingDirectory: string | null }
export type ShellError = { Validation: string } | { State: string } | { NotFound: string } | { Pty: string } | { Io: string } | { Store: string } | { Serialization: string }
export type SplitDirectionDto = "horizontal" | "vertical"
export type SplitNodeDto = { type: "pane"; paneId: string } | { type: "split"; direction: SplitDirectionDto; ratio: number; first: SplitNodeDto; second: SplitNodeDto }
export type StashEntryDto = { index: number; message: string; date: string }
export type TabView = { tabId: string; title: string; layout: SplitNodeDto; panes: PaneView[]; activePaneId: string }
export type TerminalOutputEvent = { paneId: string; runtimeSessionId: string; chunk: string }
export type ThemeModeDto = "system" | "dawn" | "midnight"
export type WorkspaceBootstrapView = { workspace: WorkspaceView; settings: SettingsView; profileCatalog: ProfileCatalogView; runtimeProjections: PaneRuntimeView[] }
export type WorkspaceCommandDto = { kind: "openTab"; layout: LayoutPresetDto | null; auto_layout: boolean; layout_tree: SplitNodeDto | null; pane_specs: PaneSpecDto[] } | { kind: "closeTab"; tab_id: string } | { kind: "setActiveTab"; tab_id: string } | { kind: "focusPane"; tab_id: string; pane_id: string } | { kind: "splitPane"; pane_id: string; direction: SplitDirectionDto; pane_spec: PaneSpecDto } | { kind: "closePane"; pane_id: string } | { kind: "swapPaneSlots"; pane_id_a: string; pane_id_b: string } | { kind: "replacePaneSpec"; pane_id: string; pane_spec: PaneSpecDto } | { kind: "restartPaneRuntime"; pane_id: string } | { kind: "renameTab"; tab_id: string; title: string }
export type WorkspaceProjectionUpdatedEvent = { workspace: WorkspaceView }
export type WorkspaceView = { activeTabId: string; tabs: TabView[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
